In [1]:
import warnings
import pandas as pd

In [2]:
warnings.filterwarnings('ignore')
df = pd.read_csv('cleaned_dataset.csv')

In [3]:
df['Date'] = pd.to_datetime(df['Date'])

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 217.6 KB

In [5]:
df.head(5)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [6]:
summary = pd.DataFrame({
    "Mean": df.mean(numeric_only=True),
    "Median": df.median(numeric_only=True),
    "Min": df.min(numeric_only=True),
    "Max": df.max(numeric_only=True),
    "Std": df.std(numeric_only=True)
})

summary

                    Mean   Median    Min      Max         Std
Quantity        2.945833    3.000   1.00     5.00    1.407557
UnitPrice     356.412750  364.210  11.39   699.93  197.177146
ItemsInCart     5.485000    5.000   1.00    10.00    2.281983
TotalPrice   1053.968300  823.615  11.39  3456.40  819.856558

In [7]:
df.describe(include='all')

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
count,1200,1200,1200,1200,1200.000000,1200.000000,1200,1200,1200,1200,1200.000000,1200,1200,1200.000000
unique,1200,NaN,1189,7,NaN,NaN,655,5,5,1200,NaN,4,5,NaN
top,ORD200000,NaN,C98474,Printer,NaN,NaN,533 Main St,Online,Cancelled,TRK37947903,NaN,FREESHIP,Instagram,NaN
freq,1,NaN,2,181,NaN,NaN,8,258,250,1,NaN,313,259,NaN
mean,NaN,2024-03-22 16:58:48,NaN,NaN,2.945833,356.412750,NaN,NaN,NaN,NaN,5.485000,NaN,NaN,1053.968300
min,NaN,2023-01-01 00:00:00,NaN,NaN,1.000000,11.390000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,11.390000
25%,NaN,2023-08-03 18:00:00,NaN,NaN,2.000000,186.062500,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,410.520000
50%,NaN,2024-03-23 00:00:00,NaN,NaN,3.000000,364.210000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,823.615000
75%,NaN,2024-11-08 12:00:00,NaN,NaN,4.000000,521.570000,NaN,NaN,NaN,NaN,7.000000,NaN,NaN,1578.475000
max,NaN,2025-06-30 00:00:00,NaN,NaN,5.000000,699.930000,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,3456.400000
std,NaN,NaN,NaN,NaN,1.407557,197.177146,NaN,NaN,NaN,NaN,2.281983,NaN,NaN,819.856558

In [8]:
product_revenue = df.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False).reset_index()

product_revenue

   Product  TotalPrice
0    Chair   195620.11
1  Printer   195612.61
2   Laptop   192126.56
3   Tablet   186568.95
4  Monitor   175651.41
5     Desk   167459.93
6    Phone   151722.39

In [9]:
quantity_sold = df.groupby('Product')['Quantity'].sum().sort_values(ascending=False).reset_index()

quantity_sold

   Product  Quantity
0    Chair       562
1  Printer       542
2   Laptop       535
3     Desk       508
4   Tablet       497
5  Monitor       480
6    Phone       411

In [10]:
(df["PaymentMethod"].value_counts(normalize=True)*100).reset_index().rename(columns={"PaymentMethod": "Percentage"})

    Percentage  proportion
0       Online   21.500000
1         Cash   20.500000
2  Credit Card   19.500000
3   Debit Card   19.333333
4    Gift Card   19.166667

In [11]:
df["OrderStatus"].value_counts()

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

In [12]:
df["ReferralSource"].value_counts()

ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 217.6 KB

In [14]:
Q1 = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers = df[(df["Quantity"]<lower)|(df["Quantity"]>upper)]

print(f'Number of Outliers are: {outliers.shape[0]}')

Number of Outliers are: 0

In [15]:
monthly_sales = df.groupby(df['Date'].dt.month)['TotalPrice'].sum().reset_index()

monthly_sales['TotalPrice'] = monthly_sales['TotalPrice'].apply(lambda x: f"${x:,.0f}")

monthly_sales

    Date TotalPrice
0      1   $124,313
1      2   $112,345
2      3   $123,841
3      4   $109,186
4      5   $135,143
5      6   $170,616
6      7    $85,785
7      8    $86,343
8      9    $69,322
9     10    $89,835
10    11    $75,493
11    12    $82,540

In [16]:
monthly_quantity = df.groupby(df['Date'].dt.month)['Quantity'].sum().reset_index()

monthly_quantity['Quantity'] = monthly_quantity['Quantity'].apply(lambda x: f"{x:,.0f}")

monthly_quantity

    Date Quantity
0      1      328
1      2      303
2      3      367
3      4      320
4      5      356
5      6      458
6      7      243
7      8      260
8      9      208
9     10      241
10    11      211
11    12      240